steps:
  - name: gcr.io/cloud-builders/git
    env:
      - branch=$BRANCH_NAME
    args:
      - '-eEuo'
      - pipefail
      - '-c'
      - |-
        echo ${branch}
        git clone --single-branch --depth=1 -b ${branch} https://github.com/softwaretester123/liquibase-gcp-test.git
    id: get_repo
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    id: welcome_script
    script: |
      chmod +x ./build_db/build_db.sh |
      ./build_db/build_db.sh
    automapSubstitutions: true
  - name: gcr.io/cloud-builders/docker
    id: build_docker_image
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/postgres/postgres:latest', '-f', 'build_db/Docker/Dockerfile', '.']
    automapSubstitutions: true
images:
  - >-
    gcr.io/$PROJECT_ID/postgres/postgres:latest